### ISSUE TITLE
请问编译ble时说找不到wireless/include应该如何解决？

### ISSUE THREAD

**Issue by MiracleLiuyx** [Huckies/qmk_port_ch582#154]
~/projects/qmk_port_ch582/build$ cmake -Dkeyboard=TychePad -Dkeymap=default .. && make -j$(nproc)
-- Found ccache: /usr/bin/ccache
-- Found mergehex: /home/miracle/.local/opt/nrf-command-line-tools/bin/mergehex
-- Found riscv-none-elf-gcc: /home/miracle/projects/qmk_port_ch582/utils/riscv-none-elf-gcc/bin/riscv-none-elf-gcc
-- Found riscv-none-elf-g++: /home/miracle/projects/qmk_port_ch582/utils/riscv-none-elf-gcc/bin/riscv-none-elf-g++
-- Found riscv-none-elf-ar: /home/miracle/projects/qmk_port_ch582/utils/riscv-none-elf-gcc/bin/riscv-none-elf-ar
-- Found riscv-none-elf-objcopy: /home/miracle/projects/qmk_port_ch582/utils/riscv-none-elf-gcc/bin/riscv-none-elf-objcopy
-- Found riscv-none-elf-objdump: /home/miracle/projects/qmk_port_ch582/utils/riscv-none-elf-gcc/bin/riscv-none-elf-objdump
CMake Warning at CMakeLists.txt:75 (message):
  CMAKE_BUILD_TYPE not set, default to 'Release'

-- Maximum optimization for speed
-- Compiling TychePad:default
-- QMK Version 0.23.1
-- QMK Build date "2023-12-18-20:57:25"
-- MOUSE_ENABLE
-- NKRO_ENABLE
-- GRAVE_ESC_ENABLE
-- ENCODER_ENABLE
-- ENCODER_MAP_ENABLE
-- UNICODEMAP_ENABLE
-- UNICODE_COMMON_ENABLE
-- VIA_ENABLE
-- COMMAND_ENABLE
-- BOOTMAGIC_ENABLE
-- RGB_MATRIX_ENABLE
-- AUXILIARY_RGB_ENABLE
-- EEPROM_ENABLE
-- EEPROM_DRIVER = custom
-- WS2812_REQUIRED
-- WS2812_DRIVER = spi
-- OLED_ENABLE
-- OLED_DRIVER = SSD1306
-- I2C_MASTER_ENABLE
-- UART_ENABLE
-- USB_ENABLE
-- BLE_ENABLE
-- ESB_ENABLE
-- ESB_ROLE = keyboard
Entering /home/miracle/projects/qmk_port_ch582/sdk/CMakeLists.txt
Exiting /home/miracle/projects/qmk_port_ch582/sdk/CMakeLists.txt
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "wireless_lib" includes non-existent path

    "/home/miracle/projects/qmk_port_ch582/qmk_porting/keyboards/TychePad/wireless/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CMakeLists.txt:
  Imported target "wireless_lib" includes non-existent path

    "/home/miracle/projects/qmk_port_ch582/qmk_porting/keyboards/TychePad/wireless/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CMakeLists.txt:
  Imported target "wireless_lib" includes non-existent path

    "/home/miracle/projects/qmk_port_ch582/qmk_porting/keyboards/TychePad/wireless/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CMakeLists.txt:
  Imported target "wireless_lib" includes non-existent path

    "/home/miracle/projects/qmk_port_ch582/qmk_porting/keyboards/TychePad/wireless/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

多谢！

**Comment by Huckies** [comment]
把 `BLE_ENABLE` 和 `ESB_ENABLE` 关了

**Comment by MiracleLiuyx** [comment]
您的意思是，这个项目只能用usb，无法使用蓝牙功能？

目前编译TychePad过不了。看了一下配置，ble是开启的。

**Comment by Huckies** [comment]
`支持有线、蓝牙、无线 2.4G（无线功能暂不开放）。`
见[Readme](https://github.com/O-H-M2/qmk_port_ch582/blob/via/README.zh-cn.md)

**Comment by MiracleLiuyx** [comment]
多谢，多谢！以为“无线功能暂不开放”仅指无线2.4G，原来也包括蓝牙。
