### ISSUE TITLE
请问蓝牙功能什么时候开放

### ISSUE THREAD

**Issue by jaaronkot** [Huckies/qmk_port_ch582#171]
你好，使用via分支编译default 配置成功，烧录到ch582f上有线也可以正常识别键盘，但是蓝牙编译的时候会报找不到 `wireless/include`头文件，因为键盘目录就没有放置这些头文件以及其他依赖，看了下之前的issue 说是位开放 蓝颜和2.4G，请问蓝牙功能有计划开放吗？

**Comment by Huckies** [comment]
暂无，有了会发大版本。

**Comment by jaaronkot** [comment]
> 暂无，有了会发大版本。

好的，非常好的项目
