### ISSUE TITLE
Unicode support doesn't work for imk64.

### ISSUE THREAD

**Issue by jactry** [Huckies/qmk_port_ch582#99]
I tried to enable the unicode feature for imk64:jactry by this diff:
```
diff --git a/qmk_porting/keyboards/imk64/keymaps/jactry/keymap.c b/qmk_porting/keyboards/imk64/keymaps/jactry/keymap.c
index 3e3866a..658f5f4 100644
--- a/qmk_porting/keyboards/imk64/keymaps/jactry/keymap.c
+++ b/qmk_porting/keyboards/imk64/keymaps/jactry/keymap.c
@@ -35,7 +35,7 @@ const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    *
    */
     [0] = LAYOUT_all(/* 0: qwerty */
-        QK_GESC,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,  KC_EQL,    KC_BSPC,
+        QK_GESC,    UC(0x3002), KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,  KC_EQL,    KC_BSPC,
         KC_TAB,     KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC,  KC_RBRC,   KC_BSLS,
         KC_LCTL,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,  KC_ENT,
         KC_LSFT,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_PGUP,  KC_UP,     KC_PGDN,
diff --git a/qmk_porting/keyboards/imk64/keymaps/jactry/rules.cmake b/qmk_porting/keyboards/imk64/keymaps/jactry/rules.cmake
index 9433e66..e900c12 100644
--- a/qmk_porting/keyboards/imk64/keymaps/jactry/rules.cmake
+++ b/qmk_porting/keyboards/imk64/keymaps/jactry/rules.cmake
@@ -1,2 +1,3 @@
 set(BLE_ENABLE OFF CACHE BOOL "KB" FORCE)
 set(ESB_ENABLE OFF CACHE BOOL "KB" FORCE)
+set(UNICODE_ENABLE ON CACHE BOOL "KB" FORCE)
```

As expected, it will input the full-width period (or says Chinese period), but actually it only inputs the number "3002".

I don't know if this is an imk64-specific issue, or a generic issue for this ch582 port. Anyway, I create this issue for tracking.
It would be appreciated if someone can test the unicode feature in other keyboards for confirming it. :D 

Thanks

**Comment by Huckies** [comment]
Please refer to this keyboard [https://github.com/O-H-M2/qmk_port_ch582/tree/via/qmk_porting/keyboards/m8rev1](url)

I believe the missing `#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS, UNICODE_MODE_WINDOWS, UNICODE_MODE_WINCOMPOSE` is critical for unicode to work.

Also @alinelena please correct me if there is any error.

**Comment by jactry** [comment]
> Please refer to this keyboard [https://github.com/O-H-M2/qmk_port_ch582/tree/via/qmk_porting/keyboards/m8rev1](url)
> 
> I believe the missing `#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS, UNICODE_MODE_WINDOWS, UNICODE_MODE_WINCOMPOSE` is critical for unicode to work.
> 
> Also @alinelena please correct me if there is any error.

Yeah, you are right. Adding a line for UNICODE_SELECTED_MODES in imk64's setup can make it working.
Thank you!

Closed.
